@startwbs
* Work Breakdown Structure (Projet Logs)
** Planning
*** Planification du projet
*** Recherches des solutions
*** Choix des technologies
** Réalisation
*** Collecte et stockage des logs
*** Indexation, filtrage et normalisation des logs
*** Visualisation et analyse des logs
** Evaluation
*** Mise en place des métriques
*** Tests (unitaires, intégration, charge)
** Livraison
*** Eléments de soutenance
*** Eléments de démo
@endwbs
